### ISSUE TITLE
I thought its free?

### ISSUE THREAD

**Issue by Blucknote** [Fuzzy-Search/chat-with-page#7]
Does I really need rely on supabase or parcel or anything that require payments? Or this some mistake?

<img width="705" alt="image" src="https://github.com/Fuzzy-Search/chat-with-page/assets/15163043/f0a3bade-6b33-4871-a999-697f3c2e70fc">

**Comment by Lurrobert** [comment]
Hey! Its 100% free. Its the old stuff I havn't removed yet, working on it!

**Comment by Blucknote** [comment]
Great! Let's keep it open until resolve

**Comment by Lurrobert** [comment]
fixed
