### ISSUE TITLE
Extension doesn't reply back

### ISSUE THREAD

**Issue by Blucknote** [Fuzzy-Search/chat-with-page#8]
Okay this is a tough one

I maked extension show input popup on hotkey and I certainly see that it making requests to openai endpoint backend:
<img width="1559" alt="image" src="https://github.com/Fuzzy-Search/chat-with-page/assets/15163043/0d750c54-6611-4b38-81f9-014bf5133ea5">

But extension doesn't show any answer after that, input popup still present.

What can i try to do or check?

Extension have 
<details>
<summary>several errors</summary>
<img width="677" alt="image" src="https://github.com/Fuzzy-Search/chat-with-page/assets/15163043/6df48014-3327-4a15-874d-e341ab789910">
<img width="704" alt="image" src="https://github.com/Fuzzy-Search/chat-with-page/assets/15163043/a178d74c-5d77-4957-8755-7fac074dbe48">
<img width="673" alt="image" src="https://github.com/Fuzzy-Search/chat-with-page/assets/15163043/58655307-012c-4937-b227-44cf024d0e79">
<img width="669" alt="image" src="https://github.com/Fuzzy-Search/chat-with-page/assets/15163043/cfb4e64e-7025-484f-8193-e23e3468b40e">
<img width="672" alt="image" src="https://github.com/Fuzzy-Search/chat-with-page/assets/15163043/72471166-5289-45ae-b34b-e741c2165c04">
</details>

It saying cannot establish connection, but api-endpoint from your repo is up and runnning
<img width="949" alt="image" src="https://github.com/Fuzzy-Search/chat-with-page/assets/15163043/d36c05b9-e93a-463b-a017-dd73f4e1c3ff">

**Comment by Lurrobert** [comment]
fixed
